### PR TITLE
Fix bug parsing set of valid OpenApi spec versions

### LINKED ISSUE #64: Exception when parsing newer OpenApi3 schemas
When parsing OpenApi **3.0.2** schemas like the [Pet Store api](https://petstore3.swagger.io/api/v3/openapi.json) with:

`eitherDecodeFileStrict openApiFile :: IO (Either String OpenApi)`

I get an exception:

```
"Error in $: Additonal field don't match for key openapi: String "3.0.0" /= String "3.0.2""
```

This is so because in https://github.com/biocad/openapi3/blob/master/src/Data/OpenApi/Internal/AesonUtils.hs#L199-L205 the check is testing for equality on the version defined in https://github.com/biocad/openapi3/blob/master/src/Data/OpenApi/Internal.hs#L1595, so newer versions like latest **3.0.3** will fail when reading. 

I thought on submitting a PR where we check for a regular expression instead of hard equality but I don't know about implications. Is this the way to go or would you approach the resolution differently?

### PR DESCRIPTION
**Pull request by tonicebrian**
The library was lacking the mandatory field `openapi` as a root element. This wasn't required before because version was fixed at `3.0.0`. This PR is intended to allow parsing all versions in the `3.0.x` range and closes #64

### CODE REVIEW

File: src/Data/OpenApi/Internal.hs [hunk 1]
```diff
@@ -1425,6 +1445,23 @@ instance ToJSON Callback where
 -- Manual FromJSON instances
 -- =======================================================================
 
+instance FromJSON OpenApiSpecVersion where
+  parseJSON = withText "OpenApiSpecVersion" $ \str ->
+            let validatedVersion :: Either String Version
+                validatedVersion = do
+                  parsedVersion <- readVersion str 
+                  upperBound <- readVersion "3.0.3" -- Latest known version that works with the spec
+                  lowerBound <- readVersion "3.0.0"
```
Comment (maksbotan) [inline src/Data/OpenApi/Internal.hs:1454]: Let's use [`makeVersion`](https://hackage.haskell.org/package/base-4.17.0.0/docs/Data-Version.html#v:makeVersion) for these static versions?

File: src/Data/OpenApi/Internal.hs [hunk 2]
```diff
@@ -1425,6 +1445,23 @@ instance ToJSON Callback where
...
+                  unless ((parsedVersion >= lowerBound) && (parsedVersion <= upperBound)) $ Left ("The provided version " <> showVersion parsedVersion <> " is out of the allowed range >=3.0.0 && <=3.0.3")
```
Comment (maksbotan) [inline src/Data/OpenApi/Internal.hs:1455]:
```suggestion
                  unless ((parsedVersion >= lowerBound) && (parsedVersion <= upperBound)) $
                      Left ("The provided version " <> showVersion parsedVersion <> " is out of the allowed range >=3.0.0 && <=3.0.3")
```

also, can you please use `showVersion` with the bounds you set in the error message?

**Review by maksbotan — COMMENTED** [review]
This PR is OK! I'll merge after these cosmetic changes.

File: src/Data/OpenApi/Internal.hs (hunk 1 above)
Comment (tonicebrian) [reply src/Data/OpenApi/Internal.hs]: Addressed in my last commit

**Comment by maksbotan** [comment]
Thanks! I'll release this on Hackage after #43 is merged.
